### ISSUE TITLE
Fix Code

### ISSUE THREAD

**Issue by PavelMoiseev** [DamirKul/cybersport-news-parser#1]
1. Ознакомиться с PEP 8. Исправить форматирование;
2. Завернуть логику в функцию, использовать для её вызова if __name__ == "__main__"
3. url = requests.get('https://www.cybersport.ru/rss/materials') - это не url, а тело запроса (request). Вынести url глобальную переменную (смотри PEP 8);
4. Тело запроса завернуть в try ... except;
5. Заполнить Readme.md - взять большую часть описания из ТЗ, посмотреть как заполняется данный документ в дургих проектах.

**Comment by DamirKul** [comment]
1. Разделены стандартные библиотеки от сторонних, изменен нейминг глобальной переменной
2. Логика парсера теперь реализована в функции parse_cybersport(), вызывается через if name == "main"
3. url записан в переменную URL_ADDRESS, тело запроса - в переменную request
4. Добавлен блок try except с указанием исключений, вызываемых raise_for_status(), timeout и RequestException для общего случая
5. Обновлено описание readme
